config/routes.rb
Rails.application.routes.draw do

  get 'contents/index'

  get 'contents/new'

  get 'contents/edit'

  get 'pages/profile'
  get '/answers/:id', to: 'answers#show' , as: "answer"
  resources :user, :controller => "user"
  get 'pages/metrics'
  get 'pages/daily_concepts'
  get 'pages/streak_tooltip'
  get 'pages/public_private_switch'

  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  resources :contents
  resources :questions do
    collection { post :import }
    resources :answers , except: :show
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'pages#home'

end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  question   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Question < ActiveRecord::Base
  validates_presence_of :question
  has_many :answers
  has_many :users, through: :answers

  def self.deliver_daily_question
    mail_hash = {}
    User.all.each do |user|
      if user.last_sent_question != -1
        if user.answers.count == Question.all.count
          user.update(last_sent_question: -1)
          UserMailer.congratulations_email(user.id).deliver_now
          puts "Congratulations!!!!"
        else
          puts "I enter here!"
          if user.last_sent_question == nil
            mail_hash[user.id] = Question.first.id
            user.update(last_sent_question: Question.first.id)
          elsif Question.where("id > ?", user.last_sent_question).first == nil
            if user.questions.include?(Question.first)
              question_true = true
              included_question = Question.where("id > ?", user.Question.first).first
              while question_true == true
                unless user.questions.include?(included_question)
                  mail_hash[user.id] = included_question.id
                  user.update(last_sent_question: included_question.id)
                  question_true = false
                end
                included_question = Question.where("id > ?", included_question).first
              end
            else
              mail_hash[user.id] = Question.first.id
              user.update(last_sent_question: Question.first.id)
            end
          else
            Question.where("id > ?", user.last_sent_question).first # To get next question to send
            question_true = true
            included_question = Question.where("id > ?", Question.find(user.last_sent_question)).first
            while question_true == true
              unless user.questions.include?(included_question)
                mail_hash[user.id] = included_question.id
                user.update(last_sent_question: included_question.id)
                question_true = false
              end
              included_question = Question.where("id > ?", included_question).first
            end
          end
        end
      end
    end
    puts mail_hash
    mail_hash
  end

  def self.deliver_mail(mail_hash)
    mail_hash.each do |user_id, question_id|
      puts "delivering question_id: #{question_id} to user_id: #{user_id}"
      UserMailer.daily_question(user_id, question_id).deliver_now
    end
  end

  def self.import(file)
    if file != nil
      CSV.foreach(file.path, headers: true) do |row|
        Question.create! row.to_hash
      end
    end
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :admin_only

  def index
    @questions = Question.all.sort
  end

  def new
    @question = Question.new()
  end

  def edit
    @question = Question.find(params[:id])
  end

  def create
    @question = Question.new(question_params)
    if Question.last.nil?
      @question.id = 1
    else
      @question.id = Question.last.id + 1
    end

    if @question.save
      redirect_to questions_path
    else
      render 'new'
    end
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      redirect_to questions_path, notice: "Se ha editado la pregunta con éxito."
    else
      render 'edit', alert: "Hubo un error y no se pudo editar la pregunta."
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to questions_path
  end

  def import
    Question.import(params[:file])
    if params.has_key?(:file)
      redirect_to questions_path, notice: "Se han importado las preguntas."
    else
      redirect_to questions_path, alert: "Debe agregar un archivo primero."
    end
  end

  private
  def question_params
    params.require(:question).permit(:question, :id)
  end

  def admin_only
    unless current_user.admin?
      redirect_to root_path, :alert => "Acceso denegado, no posee permisos como administrador"
    end
  end

end

app/views/questions/_form.html.erb
<style>
  button {
    margin-top: 20px;
  }
</style>
<div class="container">
  <h1><%= current_page %></h1>

  <%= bootstrap_form_for @question do |f| %>
    <%= render 'shared/error_messages', object: @question %>
    <%= f.text_area :question %>

    <%= f.submit form_submit %>
  <% end %>

  <%= link_to questions_path do %>
      <button class="btn btn-default" type="submit"><span class="fa fa-arrow-left"></span> Regresar</button>
  <% end %>
</div>

app/views/questions/edit.html.erb
<%= render partial: 'form', locals: { form_submit: "Editar Pregunta", current_page: "Editar Pregunta" } %>

app/views/questions/index.html.erb
<style>
  .info-paragraph {
    color: gray;
  }

  .questions-table {
    margin-top: 20px;
  }
</style>

<div class="container">
  <h1 id="title">Preguntas</h1>
  <p class="info-paragraph">Puedes agregar las preguntas a través de un archivo CSV. Lo único que debes hacer es escrbir 'question' (sin comillas) en la primera línea y las preguntas que deseas agregar en cada línea consecutiva. Las preguntas serán enviadas a los usuarios en el orden que fueron agregadas (según su Id).</p>
  <hr>
  <%= link_to new_question_path do %>
    <button class="btn btn-primary pull-right"> <span class="fa fa-plus-square"></span> Nueva Pregunta</button>
  <% end %>
  <%= form_tag import_questions_path, multipart: true do %>
    <div class="col-md-3">
      <%= file_field_tag :file, :class => 'question-upload' %>
    </div>
    <%= submit_tag "Import", :class => "btn btn-default" %>
  <% end %>
  <table class="table questions-table">
    <tr>
      <th>Id</th>
      <th>Question</th>
      <th colspan="2"></th>
    </tr>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.id %></td>
        <td><%= question.question %></td>
        <td><%= link_to "<span class='fa fa-pencil'></span>".html_safe, edit_question_path(question) %></td>
        <td><%= link_to "<span class='fa fa-trash'></span>".html_safe, question_path(question), method: :delete, data: { confirm: '¿Esta seguro que desea elminar esta pregunta?' } %></td>
      </tr>
    <% end %>
  </table>
</div>

<script>
  $(".question-upload").filestyle({icon: false});
  $('#input01').filestyle()
</script>

app/views/questions/new.html.erb
<%= render partial: 'form', locals: { form_submit: "Crear Pregunta", current_page: "Nueva Pregunta" } %>