config/routes.rb
Rails.application.routes.draw do

  get 'contents/index'

  get 'contents/new'

  get 'contents/edit'

  get 'pages/profile'
  get '/answers/:id', to: 'answers#show' , as: "answer"
  resources :user, :controller => "user"
  get 'pages/metrics'
  get 'pages/daily_concepts'
  get 'pages/streak_tooltip'
  get 'pages/public_private_switch'

  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  resources :contents
  resources :questions do
    collection { post :import }
    resources :answers , except: :show
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'pages#home'

end

app/models/content.rb
class Content < ActiveRecord::Base
  validates_presence_of :title, :content, :content_order
  enum content_order: [:izquierda, :derecha]
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  def index
    @contents = Content.all
  end

  def new
    @content = Content.new
  end

  def edit
    @content = Content.find(params[:id])
  end

  def create
    @content = Content.new(content_params)
    if @content.save
      flash[:notice] = "¡El FAQ ha sido creado correctamente!"
      redirect_to contents_path
    else
      flash[:alert] = "El FAQ no se ha podido crear, intentalo de nuevo."
      render 'new'
    end
  end

  def update
    @content = Content.find(params[:id])
    if @content.update(content_params)
      flash[:notice] = "¡El FAQ se ha actualizado correctamente!"
      redirect_to contents_path
    else
      flash[:alert] = "El FAQ no se ha podido actualizar. Inténtalo de nuevo."
      render 'edit'
    end
  end

  def destroy
    @content = Content.find(params[:id])
    @content.destroy
    redirect_to contents_path
  end

  private
  def content_params
    params.require(:content).permit(:title, :content, :content_order)
  end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_form.html.erb
<div class="container">
  <h1><%= current_page %></h1>

  <%= bootstrap_form_for @content do |f| %>
    <%= render 'shared/error_messages', object: @content %>
    <%= f.text_field :title, label: "FAQ" %>
    <%= f.text_area :content, label: "Contenido" %>
    <%= f.select :content_order, options_for_select(Content.content_orders.keys, @content.content_order), label: "Columna:" %>

    <%= f.submit form_submit %>
  <% end %>

  <%= link_to contents_path do %>
    <button class="btn btn-default" style = "margin-top: 20px">Volver</button>
  <% end %>
</div>

app/views/contents/edit.html.erb
<%= render partial: 'form', locals: { form_submit: "Editar FAQ", current_page: "Editar FAQ" } %>

app/views/contents/index.html.erb
<style>
  .questions-table {
    margin-top: 20px;
  }
</style>

<div class="container">
  <h1 id="title">FAQs</h1>
  <hr>
  <%= link_to new_content_path do %>
    <button class="btn btn-primary pull-right"> <span class="fa fa-plus-square"></span> Nuevo FAQ</button>
  <% end %>
  <table class="table questions-table">
    <tr>
      <th>FAQ</th>
      <th>Contenido</th>
      <th colspan="2"></th>
    </tr>
    <% @contents.each do |content| %>
      <tr>
        <td><%= content.title %></td>
        <td><%= content.content %></td>
        <td><%= link_to "<span class='fa fa-pencil'></span>".html_safe, edit_content_path(content) %></td>
        <td><%= link_to "<span class='fa fa-trash'></span>".html_safe, content_path(content), method: :delete, data: { confirm: '¿Esta seguro que desea elminar esta pregunta?' } %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/contents/new.html.erb
<%= render partial: 'form', locals: { form_submit: "Crear FAQ", current_page: "Nuevo FAQ" } %>