config/routes.rb
Rails.application.routes.draw do

  get 'contents/index'

  get 'contents/new'

  get 'contents/edit'

  get 'pages/profile'
  get '/answers/:id', to: 'answers#show' , as: "answer"
  resources :user, :controller => "user"
  get 'pages/metrics'
  get 'pages/daily_concepts'
  get 'pages/streak_tooltip'
  get 'pages/public_private_switch'

  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  resources :contents
  resources :questions do
    collection { post :import }
    resources :answers , except: :show
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'pages#home'

end

app/views/pages/_firefox__clippath_profile.html.erb
<style>
   .profile-photo-name figure img {
    z-index:100;
    position:absolute;
    left:-11px;
    top:-11px;
    clip-path:  polygon(50% 0%, 100% 50%, 50% 100%, 0% 50%);
    -ms-clip-path: polygon(50% 0%, 100% 50%, 50% 100%, 0% 50%);
    -moz-clip-path: polygon(50% 0%, 100% 50%, 50% 100%, 0% 50%);
    -webkit-clip-path:  polygon(50% 0%, 100% 50%, 50% 100%, 0% 50%);
    clip-path: url(#clip);
    width:100px;
    -ms-transform: rotate(-45deg);
    -webkit-transform: rotate(-45deg);
    transform: rotate(-45deg);
    overflow: hidden;
  }

  .square  {
    margin-left: 20px;
    border: 1px solid #F3F3F3;
    height:80px;
    width:80px;
    -ms-transform: rotate(45deg);
    -webkit-transform: rotate(45deg);
    transform: rotate(45deg);
    z-index: 100;
    position: relative;
    background: white;

  }
</style>

app/views/pages/_firefox_clippath_profile.html.erb
<style>
   .profile-photo-name figure img {
    z-index:100;
    position:absolute;
    left:-11px;
    top:-11px;
    clip-path:  polygon(50% 0%, 100% 50%, 50% 100%, 0% 50%);
    -ms-clip-path: polygon(50% 0%, 100% 50%, 50% 100%, 0% 50%);
    -moz-clip-path: polygon(50% 0%, 100% 50%, 50% 100%, 0% 50%);
    -webkit-clip-path:  polygon(50% 0%, 100% 50%, 50% 100%, 0% 50%);
    clip-path: url(#clip);
    width:100px;
    -ms-transform: rotate(-45deg);
    -webkit-transform: rotate(-45deg);
    transform: rotate(-45deg);
    overflow: hidden;
  }

  .square  {
    margin-left: 20px;
    border: 1px solid #F3F3F3;
    height:80px;
    width:80px;
    -ms-transform: rotate(45deg);
    -webkit-transform: rotate(45deg);
    transform: rotate(45deg);
    z-index: 100;
    position: relative;
    background: white;

  }
</style>

app/views/pages/_script_profile.html.erb
<script>
  $(document).on('ready page:load', function () {
    $(document).ready(function() {
      var addStreakTooltip = function() {
        $.getJSON( "/pages/streak_tooltip?user=" +  "<%= @user.id %>" ).done(function( response ) {
          console.log(response)
          for(i = 0; i < response.length; i++) {
            var public_answer_content = function() {
              var public_answer = response[i].public_answer
              if(public_answer == true) {
                return '<span>Esta respuesta es <strong>pública</strong>.</span>'
              } else {
                return '<span>Esta respuesta es <strong>privada</strong>.</span>'
              }
            }
            $('.' + response[i].answer + '.tooltip').tooltipster({
              content: $(' <span><strong>Pregunta: </strong>' + response[i].question + '</span><br><span><strong>Fecha: </strong>' + response[i].day + '</span> <br>' + public_answer_content() + '<br><span>Para ver tu respuesta haz click </span> <a href="/answers/'+ response[i].answer +'">aquí.</a>'),
              interactive: true
            })
          }
        }).fail(function( jqxhr, textStatus, error ) {
          var err = textStatus + ", " + error;
          console.log( "Request Failed: " + err );
        });
      }
      addStreakTooltip();
      $('i.public-private').on('click', function() {
        console.log('clicked');
        var className = $(this).hasClass('fa-unlock-alt');
        var answer_id = $(this).find('div').text();
        if (className == true) {
          console.log("De verde a rojo")
          $.getJSON( "/pages/public_private_switch?answer_id=" +  answer_id ).done(function( response ) {
            $('.public-private').removeClass('fa-unlock-alt')
            $('.public-private').addClass('fa-lock')
            $('*').filter(function() {
              return $(this).data('tooltipsterNs');
            }).tooltipster('destroy');
            addStreakTooltip();
          }).fail(function( jqxhr, textStatus, error ) {
            var err = textStatus + ", " + error;
            console.log( "Request Failed: " + err );
          });
        } else {
          console.log("De rojo a verde")
          $.getJSON( "/pages/public_private_switch?answer_id=" +  answer_id ).done(function( response ) {
            $('.public-private').removeClass('fa-lock')
            $('.public-private').addClass('fa-unlock-alt')
            $('*').filter(function() {
              return $(this).data('tooltipsterNs');
            }).tooltipster('destroy');
            addStreakTooltip();
          }).fail(function( jqxhr, textStatus, error ) {
            var err = textStatus + ", " + error;
            console.log( "Request Failed: " + err );
          });
        }
      })
});
$( ".answer .options a.btn-toggle-1" ).on( "click", function( event ) {event.preventDefault();});
jQuery(function() {
  return $("[data-behavior='delete']").on("click", function(e) {
    e.preventDefault();
    _this = $(this).attr('href');
    console.log(_this);
    return swal({
      title: '¿ Estás seguro ?',
      type: 'info',
      showCancelButton: true,
      confirmButtonColor: '#DD6B55',
      confirmButtonText: 'Sí, borrar',
      cancelButtonText: 'No',
      closeOnConfirm: false,
      closeOnCancel: true,
      showLoaderOnConfirm: true,
      allowOutsideClick: true
    }, (function(_this) {
      console.log(_this);
      return function(confirmed) {
        if (confirmed) {
          $.ajax({
            url: $(_this).attr("href"),
            dataType: "JSON",
            method: "DELETE",
            success: function() {
              location.reload();
            // return swal( 'Tu respuesta ha sido borrada.');
          }
        });
        } else {
          swal('Tu respuesta no fue borrada.');
        }
      };
    })(this));
  });
});
});
</script>

app/views/pages/_welcome.html.erb
<% if current_user.sign_in_count == 1 %>
<div class="row">
  <div class="col-xs-12 col-sm-8 col-md-offset-2 top-container">
  <h1>MENSAJE DE BIENVENIDA</h1>
  </div>
</div>
<% end %>

app/views/pages/home.html.erb
<div id="home">

  <div class="hero-unit">
    <div class="svg-line-top dotted-hide-show">

      <div style="margin-width:35%; height:60px;"></div>
      <div style="margin-left:35%;width:15.5%;  border-bottom: 1px dotted #FFF;"></div>
      <div style="width:50.5%; height:68px; border-right: 1px dotted #FFF;"></div>
      <div style="width:50.5%; height:225px; border-right: 1px dotted #AEAEAE;"></div>
    </div>
    <div class="bg-wrapper">
      <div class="container text-center">
        <div class="row">
          <div class="col-lg-4 col-lg-offset-1 col-md-5  col-xs-6">
            <p class="home-puch-text">Como le explicarias a un niño de 12 años<br><span>¿?</span></p>
          </div>
          <div class="col-lg-4 col-lg-offset-2 col-md-4 col-md-offset-3 col-xs-5 col-xs-offset-1">
            <figure class="home-kid">
              <%= image_tag "kid.png" %>
            </figure>
          </div>
        </div>
      </div>
    </div>
  </div>
  <section class="section century-skills">
    <h2><strong>Responde una pregunta al día</strong> y aprende las habilidates más importantes del siglo XXI</h2>
    <div  style="margin-top:20px; width:50.5%; height:40px; border-right: 1px dotted #AEAEAE;"></div>
    <h2><strong>¿Cómo funciona?</strong></h2>
    <div class="dotted-hide-show" style="width:50.5%; height:100px; border-right: 1px dotted #AEAEAE;"></div>
    <div class="dotted-hide-show" style="margin-left:26.5%; width:47.5%; border-bottom: 1px dotted #AEAEAE;"></div>
  </section>
  <section class="section">
    <div class="container how-works">

   <div class="block-grid-lg-4 block-grid-md-3 block-grid-sm-2 block-grid-xs-2">

      <div class="block-grid-item">
        <figure>
          <svg version="1.1" x="0px" y="0px" width="152.2px" height="152.2px" viewBox="0 0 152.2 152.2" enable-background="new 0 0 152.2 152.2" xml:space="preserve">
            <path fill="#00BF69" d="M76.1,152.2c-41.4,0-75.6-33.7-76.1-75.2C-0.2,56.7,7.4,37.5,21.6,23S54.8,0.3,75.2,0l1,0
            c41.4,0,75.6,33.7,76.1,75.2c0.3,20.3-7.4,39.5-21.6,54.1c-14.2,14.6-33.2,22.7-53.5,23L76.1,152.2z M76.1,1.3l-1,0
            c-20,0.2-38.7,8.3-52.6,22.6C8.6,38.2,1.1,57.1,1.3,77.1c0.5,40.7,34.1,73.9,74.8,73.9l1,0c20-0.2,38.7-8.3,52.6-22.6
            c14-14.3,21.5-33.2,21.3-53.2C150.4,34.4,116.9,1.3,76.1,1.3z M100.5,55.5v3.9L76.1,74.7L51.7,59.4v-3.9H100.5 M101.8,54.2h-1.3
            H51.7h-1.3v1.3v3.9v0.7l0.6,0.4l24.4,15.3l0.7,0.4l0.7-0.4l24.4-15.3l0.6-0.4v-0.7v-3.9V54.2L101.8,54.2z M100.5,63.4v24.7H51.7
            V63.4l24.4,15.2L100.5,63.4 M101.8,61.1l-2,1.2L76.1,77.1L52.4,62.3l-2-1.2v2.3v24.7v1.3h1.3h48.8h1.3v-1.3V63.4V61.1L101.8,61.1z"/>
          </svg>
        </figure>
        <h3><strong>1. </strong>Recibe una pregunta al día</h3>
      </div>
      <div class="block-grid-item">
        <figure>
          <svg version="1.1" x="0px" y="0px" width="152.2px" height="152.2px" viewBox="0 0 152.2 152.2" enable-background="new 0 0 152.2 152.2" xml:space="preserve">
            <path fill="#00BF69" d="M76.1,152.2c-41.4,0-75.6-33.7-76.1-75.2C-0.2,56.7,7.4,37.5,21.6,23S54.8,0.3,75.2,0l1,0
            c41.4,0,75.6,33.7,76.1,75.2c0.3,20.3-7.4,39.5-21.6,54.1c-14.2,14.6-33.2,22.7-53.5,23L76.1,152.2z M76.1,1.3l-1,0
            c-20,0.2-38.7,8.3-52.6,22.6C8.6,38.2,1.1,57.1,1.3,77.1c0.5,40.7,34.1,73.9,74.8,73.9l1,0c20-0.2,38.7-8.3,52.6-22.6
            c14-14.3,21.5-33.2,21.3-53.2C150.4,34.4,116.9,1.3,76.1,1.3z M106.5,89.8h-26c-1.6,0-2.8-1.3-2.8-2.8V72.4h-3V87
            c0,1.6-1.3,2.8-2.8,2.8h-26c-1.6,0-2.8-1.3-2.8-2.8V74.6h-4.3v-7.8h4.3v-1.5c0-1.6,1.3-2.8,2.8-2.8h26c1.6,0,2.8,1.3,2.8,2.8v1.5h3
            v-1.5c0-1.6,1.3-2.8,2.8-2.8h26c1.6,0,2.8,1.3,2.8,2.8v1.5h4.3v7.8h-4.3V87C109.3,88.5,108,89.8,106.5,89.8z M73.3,71.1h5.6V87
            c0,0.8,0.7,1.5,1.5,1.5h26c0.8,0,1.5-0.7,1.5-1.5V73.3h4.3v-5.2H108v-2.8c0-0.8-0.7-1.5-1.5-1.5h-26c-0.8,0-1.5,0.7-1.5,1.5v2.8
            h-5.6v-2.8c0-0.8-0.7-1.5-1.5-1.5h-26c-0.8,0-1.5,0.7-1.5,1.5v2.8h-4.3v5.2h4.3V87c0,0.8,0.7,1.5,1.5,1.5h26c0.8,0,1.5-0.7,1.5-1.5
            V71.1z M102.1,85.5H84.8c-1.6,0-2.8-1.3-2.8-2.8v-13c0-1.6,1.3-2.8,2.8-2.8h17.3c1.6,0,2.8,1.3,2.8,2.8v13
            C105,84.2,103.7,85.5,102.1,85.5z M84.8,68.1c-0.8,0-1.5,0.7-1.5,1.5v13c0,0.8,0.7,1.5,1.5,1.5h17.3c0.8,0,1.5-0.7,1.5-1.5v-13
            c0-0.8-0.7-1.5-1.5-1.5H84.8z M67.4,85.5H50.1c-1.6,0-2.8-1.3-2.8-2.8v-13c0-1.6,1.3-2.8,2.8-2.8h17.3c1.6,0,2.8,1.3,2.8,2.8v13
            C70.3,84.2,69,85.5,67.4,85.5z M50.1,68.1c-0.8,0-1.5,0.7-1.5,1.5v13c0,0.8,0.7,1.5,1.5,1.5h17.3c0.8,0,1.5-0.7,1.5-1.5v-13
            c0-0.8-0.7-1.5-1.5-1.5H50.1z"/>
          </svg>
        </figure>
        <h3><strong>2. </strong>Busca en internet</h3>
      </div>
      <div class="block-grid-item">
        <figure>
          <svg version="1.1" x="0px" y="0px" width="152.2px" height="152.2px" viewBox="0 0 152.2 152.2" enable-background="new 0 0 152.2 152.2" xml:space="preserve">
            <path fill="#00BF69" d="M76.1,152.2c-41.4,0-75.6-33.7-76.1-75.2C-0.5,35.1,33.2,0.5,75.2,0l1,0c41.4,0,75.6,33.7,76.1,75.2
            c0.5,42-33.2,76.5-75.2,77.1L76.1,152.2z M76.1,1.3l-1,0C33.9,1.8,0.8,35.8,1.3,77.1c0.5,40.7,34.1,73.9,74.8,73.9l0.9,0
            c41.3-0.5,74.4-34.5,73.9-75.7C150.4,34.4,116.9,1.3,76.1,1.3z M108.7,99.5H43.6c-2.8,0-5-2.2-5-5V52.7h75v41.9
            C113.6,97.3,111.4,99.5,108.7,99.5z M39.9,54v40.6c0,2,1.7,3.7,3.7,3.7h65.1c2,0,3.7-1.7,3.7-3.7V54H39.9z M107.1,93h-7.8v-7.8h7.8
            V93z M100.6,91.7h5.2v-5.2h-5.2V91.7z M96.3,93H56v-7.8h40.3V93z M57.3,91.7H95v-5.2H57.3V91.7z M52.9,93h-7.8v-7.8h7.8V93z
            M46.4,91.7h5.2v-5.2h-5.2V91.7z M107.1,82.2h-7.8v-7.8h7.8V82.2z M100.6,80.9h5.2v-5.2h-5.2V80.9z M96.3,82.2h-7.8v-7.8h7.8V82.2z
            M89.8,80.9H95v-5.2h-5.2V80.9z M85.5,82.2h-7.8v-7.8h7.8V82.2z M78.9,80.9h5.2v-5.2h-5.2V80.9z M74.6,82.2h-7.8v-7.8h7.8V82.2z
            M68.1,80.9h5.2v-5.2h-5.2V80.9z M63.8,82.2H56v-7.8h7.8V82.2z M57.3,80.9h5.2v-5.2h-5.2V80.9z M52.9,82.2h-7.8v-7.8h7.8V82.2z
            M46.4,80.9h5.2v-5.2h-5.2V80.9z M107.1,71.4h-7.8v-7.8h7.8V71.4z M100.6,70.1h5.2v-5.2h-5.2V70.1z M96.3,71.4h-7.8v-7.8h7.8V71.4z
            M89.8,70.1H95v-5.2h-5.2V70.1z M85.5,71.4h-7.8v-7.8h7.8V71.4z M78.9,70.1h5.2v-5.2h-5.2V70.1z M74.6,71.4h-7.8v-7.8h7.8V71.4z
            M68.1,70.1h5.2v-5.2h-5.2V70.1z M63.8,71.4H56v-7.8h7.8V71.4z M57.3,70.1h5.2v-5.2h-5.2V70.1z M52.9,71.4h-7.8v-7.8h7.8V71.4z
            M46.4,70.1h5.2v-5.2h-5.2V70.1z"/>
          </svg>
        </figure>
        <h3><strong>3. </strong>Responde la pregunta</h3>
      </div>
      <div class="block-grid-item">
        <figure>
          <svg version="1.1" x="0px" y="0px" width="152.2px" height="152.2px" viewBox="0 0 152.2 152.2" enable-background="new 0 0 152.2 152.2" xml:space="preserve">
            <path fill="#00BF69" d="M76.1,152.2c-41.4,0-75.6-33.7-76.1-75.2C-0.2,56.7,7.4,37.5,21.6,23S54.8,0.3,75.2,0l1,0
            c41.4,0,75.6,33.7,76.1,75.2c0.3,20.3-7.4,39.5-21.6,54.1c-14.2,14.6-33.2,22.7-53.5,23L76.1,152.2z M76.1,1.3l-1,0
            c-20,0.2-38.7,8.3-52.6,22.6C8.6,38.2,1.1,57.1,1.3,77.1c0.5,40.7,34.1,73.9,74.8,73.9l1,0c20-0.2,38.7-8.3,52.6-22.6
            c14-14.3,21.5-33.2,21.3-53.2C150.4,34.4,116.9,1.3,76.1,1.3z M91,52L64.6,76.3l-13-7L91,52 M98.4,47.2L48.4,69.1L64.8,78L98.4,47.2
            L98.4,47.2z M96.4,52.3l-7.9,36.8l-17.3-9.3L96.4,52.3 M98.9,47.4L68.8,80.2l20.7,11.1L98.9,47.4L98.9,47.4z M63.4,95.8V80.6
            l12.8,6.9L63.4,95.8z M64.9,83v10.1l8.5-5.5L64.9,83z"/>
          </svg>
        </figure>
        <h3><strong>4. </strong>Comparte tu pregunta</h3>
      </div>
      </div>
    </section>
    <section class="section faq">
      <h2><strong>Preguntas Frecuentes</strong></h2>
      <div class="container">
        <div class="row">
          <div class="col-sm-6">
            <% @content_column_1.each do |content| %>
              <h3><%= content.title %></h3>
              <p><%= markdown content.content %></p>
            <% end %>
          </div>
          <div class="col-sm-6">
            <% @content_column_2.each do |content| %>
              <h3><%= content.title %></h3>
              <p><%= markdown content.content %></p>
            <% end %>
          </div>
          </div>
        </div>
      </section>
    </div>
    <script>
      $(function(){
        $(".hero-unit p span").typed({
          strings: ["¿Qué es memoria RAM?", "¿Qué es internet?", "¿Qué es programación?"],
          typeSpeed: 100,
          backDelay: 500
        });
      });
    </script>

app/views/pages/metrics.html.erb
<style>
  .admin-dashboard {
    margin-top: 10px;
  }

  .status {
      font-family: 'Source Sans Pro', sans-serif;
  }

  .status .panel-title {
      font-family: 'Oswald', sans-serif;
      font-size: 54px;
      font-weight: bold;
      color: #fff;
      line-height: 45px;
      padding-top: 20px;
      letter-spacing: -0.8px;
  }
</style>
<div class="container admin-dashboard">
  <h1>Dashboard de Administrador</h1>
  <div class="row">
    <div class="col-xs-6 col-md-3 col-md-offset-1">
      <div class="panel status panel-success">
        <div class="panel-heading">
          <h1 class="panel-title text-center"><%= @answers.count %></h1>
        </div>
        <div class="panel-body text-center">
          <strong>Respuestas Totales</strong>
        </div>
      </div>
    </div>
    <div class="col-xs-6 col-md-3">
      <div class="panel status panel-success">
        <div class="panel-heading">
          <h1 class="panel-title text-center"><%= @users.count %></h1>
        </div>
        <div class="panel-body text-center">
          <strong>Usuarios Registrados</strong>
        </div>
      </div>
    </div>
    <div class="col-xs-6 col-md-3">
      <div class="panel status panel-info">
        <div class="panel-heading">
          <% if @answers.count > 0 %>
            <h1 class="panel-title text-center"><%= average_answers_per_user %></h1>
          <% else %>
            <h1 class="panel-title text-center">0</h1>
          <% end %>
        </div>
        <div class="panel-body text-center">
          <strong>Respuestas promedio por usuario</strong>
        </div>
      </div>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Número de Respuestas Diarias</h3>
    </div>
    <div class="panel-body">
      <div id="myfirstchart" style="height: 250px;"></div>
    </div>
  </div>

</div>

<script>

  daily_data = function() {
    $.ajax({
            url: "/pages/daily_concepts",
            type: "GET",
          }).done( function(response) {
            console.log(response[0])
            return response
          });
  }

  var render_map = function(daily_data) {
    new Morris.Line({
      // ID of the element in which to draw the chart.
      element: 'myfirstchart',
      // Chart data records -- each entry in this array corresponds to a point on
      // the chart.
      data: daily_data,
      // The name of the data record attribute that contains x-values.
      xkey: 'day',
      xLabels: 'day',
      // A list of names of data record attributes that contain y-values.
      ykeys: ['answer'],
      // Labels for the ykeys -- will be displayed when you hover over the
      // chart.
      labels: ['Answer']
    });
  }

  $.getJSON( "/pages/daily_concepts" ).done(function( response ) {
    console.log(response[30]);
    render_map(response);
  }).fail(function( jqxhr, textStatus, error ) {
      var err = textStatus + ", " + error;
      console.log( "Request Failed: " + err );
  });


</script>

app/views/pages/profile.html.erb
<section class="section section-profile">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2">
        <div class="profile-photo-name">
          <div class="square">
            <figure>
              <%= image_tag @user.avatar %>
              <svg>
                <clipPath id="clip">
                  <polygon points="50 0, 100 50, 50 100, 0 50"></polygon>
                </clipPath>
              </svg>
            </figure>
          </div>
          <div class="right-block">
            <h3><%= @user.first_name %></h3>
            <div class="dropdown dropdown-container pull-right">
              <button class="btn btn-default dropdown-toggle"  id="menu-options" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-cog"></i>
              </button>
              <ul class="dropdown-menu" aria-labelledby="menu-options">
                <li class="text-right">
                  <%= link_to " Editar datos  <span class='fa fa-pencil'></span>".html_safe , edit_user_path(current_user)  %>
                </li>
                <li class="text-right">
                  <%= link_to "Cancelar cuenta  <span class='fa fa-warning'></span>".html_safe, registration_path(@user), data: { confirm: "Estas seguro que deseas cancelar tu cuenta?" }, method: :delete %>
                </li>
              </ul>
            </div>
            <p class="pull-right"><%= @user.answers.count %><span>respuestas</span></p>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <% if day_streak(@user).count > 0 %>
      <div class="col-xs-12 col-md-6 col-md-offset-3">
        <h3 class="text-center"><strong>Días seguidos</strong></h3>
        <ul class="streak-squares">
          <% day_streak(@user).each_with_index do |answer, index| %>
          <li><a href="/answers/<%=  answer[:answer].first.id %>" class="<%= answer[:answer].first.id %> tooltip"><%= index + 1 %></a></li>
          <% end %>
        </ul>
      </div>
      <% end %>
    </div>
    <% if day_streak(@user).count > 0 %>
    <div class="dotted-hide-show" style="margin-top:30px;width:50%; height:50px; border-right: 1px dotted #AEAEAE;"></div>
    <% end %>
    <h3 class="text-center"><strong>respuestas</strong></h3>
    <div class="dotted-hide-show" style="margin-top:30px;width:50%; height:50px; border-right: 1px dotted #AEAEAE;"></div>

    <% @user.answers.sort_by(&:created_at).reverse.each_with_index do |answer, index| %>

    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <div class="answer">
          <div class="options pull-left">
            <ul class="list-inline">
              <li>
                <%= link_to '<i class="fa fa-pencil-square-o"></i>'.html_safe, edit_question_answer_path(answer.question, answer) %>
              </li>
              <% if answer.public_answer == true %>
              <li>
                <a class="btn-toggle-1" href="#"><i class="public-private fa fa-unlock-alt"><div class="hidden"><%= answer.id %></div></i></a>
              </li>
              <% else %>
              <li>
                <a class="btn-toggle-1" href="#">
                  <i class="public-private fa fa-lock"><div class="hidden"><%= answer.id %></div></i>
                </a>
              </li>
              <% end %>
              <li>
                <%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, question_answer_path(answer.question, answer), data: { behavior: 'delete' } %>
              </li>
            </ul>
          </div>
          <div class="date pull-right">
            <span class="day"><%= answer.created_at.strftime("%d") %></span>
            <span class="month"><%= answer.created_at.strftime("%B").first(3) %></span>
            <span class="year"><%= answer.created_at.strftime("%Y") %></span>
          </div>
          <div class="number">
            <%= @user.answers.sort_by(&:created_at).reverse.count - index %>
          </div>
          <%= link_to "<h3> #{  answer.question.question  }</h3>#{  markdown answer.answer  }".html_safe, answer_path(answer), class: 'answer-link' %>
        </div>
      </div>
    </div>

    <% if answer != @user.answers.sort_by(&:created_at).reverse.last %>
      <div class="dotted-hide-show" style="margin-top:30px;width:50%; height:50px; border-right: 1px dotted #AEAEAE;"></div>
    <% else %>
      <br><br>
      <% end %>
    <% end %>

  </div>
</section>
<%= render 'pages/firefox_clippath_profile' %>
<%= render 'pages/script_profile' %>