config/routes.rb
Rails.application.routes.draw do

  get 'contents/index'

  get 'contents/new'

  get 'contents/edit'

  get 'pages/profile'
  get '/answers/:id', to: 'answers#show' , as: "answer"
  resources :user, :controller => "user"
  get 'pages/metrics'
  get 'pages/daily_concepts'
  get 'pages/streak_tooltip'
  get 'pages/public_private_switch'

  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  resources :contents
  resources :questions do
    collection { post :import }
    resources :answers , except: :show
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'pages#home'

end

app/views/layouts/_alerts.html.erb
<div class="alerts">
  <% if flash[:alert] %>
    <div class="alertOffset">
        <div class="alert alert-danger text-center" role="alert">
          <%=flash[:alert]%>
          <span class="right-text text-right">X</span>
      </div>
    </div>
  <%end%>

  <% if flash[:notice] %>
    <div class="alertOffset">
        <div class="alert alert-success text-center" role="alert">
          <%=flash[:notice]%>
          <span class="text-right">X</span>
        </div>
    </div>
  <%end%>
</div>

app/views/layouts/_favicons_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">

app/views/layouts/_footer.html.erb
<div id="footer-clear"></div>
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-4 text-center">
        <a target="_blank" href="http://www.kaizendevs.com">
          <figure>
            <%= render 'layouts/footer/svg_kaizendevs' %>
          </figure>
        </a>
      </div>
      <div class="col-xs-4 text-center">
        <a target="_blank" href="http://www.makeitreal.camp">
          <figure>
            <%= render 'layouts/footer/svg_makeitreal' %>
          </figure>
        </a>
      </div>
      <div class="col-xs-4 text-center">
        <a target="_blank" href="/">
          <figure>
          <%= render 'layouts/footer/svg_cienpreguntas' %>
          </figure>
        </a>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default nav-home">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
      <span class="sr-only">MENU</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><%= image_tag(asset_path('logo-white.png'), class: 'logo img-responsive') %></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <% if current_user.admin? %>
            <li><%= link_to "Métricas", pages_metrics_path %></li>
            <li><%= link_to "Todos los Usuarios", user_index_path %></li>
            <li><%= link_to 'Administrar Preguntas', questions_path %></li>
            <li><%= link_to 'FAQs', contents_path %></li>
          <% end %>
          <li><%= link_to 'Mi Perfil', pages_profile_path %></li>
          <li><%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Ingresar", new_user_session_path %></li>
          <li><%= link_to "Ingresar con Facebook", user_omniauth_authorize_path(:facebook) %></li>
          <li>
            <p class="navbar-btn">
              <%= link_to "Crea cuenta", new_user_registration_path, class: "btn btn-default" %>
            </p>
          </li>
        <% end %>
      </ul>
    </div>
    <ul class="nav navbar-nav navbar-right">

    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CienPreguntas</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= render 'layouts/favicons_links' %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/tooltipster/3.3.0/css/tooltipster.min.css">

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <script>
    window.fbAsyncInit = function() {
      FB.init({
        appId      : '1660814297468391',
        xfbml      : true,
        version    : 'v2.3'
      });
    };

    (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
  </script>

  <%= render 'layouts/nav' %>

  <%= render 'layouts/alerts' %>
  <%#= render 'layouts/navhome' %>
  <%= yield %>

  <%= render 'layouts/footer' %>


</body>
</html>
<script>
  $(".alert").fadeIn(500).css("opacity","0.85").delay( 6000 ).fadeOut( 1000 );
  $('.alerts').on('click','.alert',function(){ $(this).remove() });
</script>
<script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/tooltipster/3.3.0/js/jquery.tooltipster.min.js"></script>